PUTFILE "!Boot.txt", "!Boot", &FFFFFF
PUTBASIC "LOADER.bas", "LOADER"
PUTBASIC "Meteor Storm.bas", "METEOR"
PUTBASIC "Alien Invaders.bas", "ALIEN"
PUTBASIC "Bananas.bas", "BANANAS"
PUTBASIC "Spider.bas", "SPIDER"
PUTBASIC "Target Practise.bas", "TARGET"
PUTBASIC "Fortune Teller.bas", "FORTUNE"
PUTBASIC "Grand Slalom.bas", "GRAND"
PUTBASIC "Laser Locksmith.bas", "LASER"
PUTBASIC "Blockbuster.bas", "BLOCKB"
PUTBASIC "Mu Torere.bas", "MUTORER"
PUTBASIC "Cops and Robbers.bas", "COPS"
PUTBASIC "Sorcerer's Steps.bas", "SORCER"
PUTBASIC "Parcel Drop.bas", "PARCEL"
PUTBASIC "Forgery.bas", "FORGERY"